# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "hapi"
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Robert Schultheis"]
  s.date = "2013-05-08"
  s.description = "convention based approach to interfacing with an HTTP JSON API."
  s.email = "rob@knewton.com"
  s.executables = ["hapi"]
  s.extra_rdoc_files = [
    "LICENSE.txt"
  ]
  s.files = [
    ".rspec",
    "Gemfile",
    "LICENSE.txt",
    "Rakefile",
    "Readme.md",
    "VERSION",
    "bin/hapi",
    "example/hapi.yml",
    "example/owm_hapis/weather_hapis.rb",
    "example/temperatures.rb",
    "hapi.gemspec",
    "lib/hapi.rb",
    "lib/hapi/blankslate.rb",
    "lib/hapi/configuration.rb",
    "lib/hapi/helpers.rb",
    "lib/hapi/http_service.rb",
    "lib/hapi/json_helpers.rb",
    "lib/hapi/log.rb",
    "spec/configuration_spec.rb",
    "spec/hapi_spec.rb",
    "spec/http_service_spec.rb",
    "spec/json_helpers_spec.rb",
    "spec/resources/example_config.yml",
    "spec/resources/hapi.yml",
    "spec/resources/syntax_error_hapis/eval_error_hapis.rb",
    "spec/resources/twitter_hapis/oauth_hapis.rb",
    "spec/resources/twitter_hapis/timeline_hapis.rb",
    "spec/rspec_helper_spec.rb",
    "spec/support/require_all_lib_files.rb",
    "spec/support/spec_helper.rb"
  ]
  s.homepage = "http://github.com/knewton/hapi"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.24"
  s.summary = "Make calls to HTTP JSON APIs with hapiness"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<json>, [">= 0"])
      s.add_development_dependency(%q<rspec>, [">= 0"])
      s.add_development_dependency(%q<pry>, [">= 0"])
      s.add_development_dependency(%q<awesome_print>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
    else
      s.add_dependency(%q<json>, [">= 0"])
      s.add_dependency(%q<rspec>, [">= 0"])
      s.add_dependency(%q<pry>, [">= 0"])
      s.add_dependency(%q<awesome_print>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
    end
  else
    s.add_dependency(%q<json>, [">= 0"])
    s.add_dependency(%q<rspec>, [">= 0"])
    s.add_dependency(%q<pry>, [">= 0"])
    s.add_dependency(%q<awesome_print>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
  end
end

