---
services:
  myapi:
    hostname: 'myapi.com'
    default_headers:
      user-agent: 'RSpec'
      test: '0'

  myotherapi:
    hostname: 'myotherapi.com'

environments:
  dev:
    myapi:
      hostname: 'dev.myapi.com'
      port: 123  
      default_headers:
        user-agent: 'RSpec test'
        test: '1'

  staging:
    myapi:
      hostname: 'staging.myapi.com'
      port: 456
      ignore_ssl_cert: true
